version: "3.2"
services:
  pgadmin:
      image: "docker.io/dpage/pgadmin4"
      environment:
        - PGADMIN_DEFAULT_EMAIL=lunatree@lunatree.com
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_DISABLE_POSTFIX=true
      ports:
         - "8080:80"
         - "8443:443"
  db:
      image: "docker.io/postgres"
      environment:
          - POSTGRES_USER=luna
          - POSTGRES_PASSWORD=luna
      ports:
          - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data:z
